.\" Manpage for wordfreq.
.TH WORDFREQ "1" "2018" "wordfreq" "User Commands"
.SH NAME
wordfreq \- Output the most frequently used words in the input file.
.SH DESCRIPTION
This program parses an input file and returns the most frequently used words with their frequency.
In this context a word is a continuous sequence of characters from 'a' to 'z'.
The words are case-insensitive, so uppercase letters are always mapped in lowercase.
.SS "Usage:"
.IP
wordfreq <FILE> [MAX_RESULTS]
.SH AUTHOR
Nicola Asuni (info@tecnick.com)
.SH COPYRIGHT
(c) 2018 Nicola Asuni - Tecnick.com
