language: c
os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - alien
    - astyle
    - debhelper
    - devscripts
    - dh-make
    - doxygen
    - fakeroot
    - lcov
    - pkg-config
    - rpm

install:
  - gem install coveralls-lcov

script:
  - make all

after_success:
  - coveralls-lcov /home/travis/build/tecnickcom/wordfreq/target/test/coverage/wordfreq.info
